import { useDuplicates } from '../hooks/useApi';
import { PageHeader } from '../components/PageHeader';
import { StatCard } from '../components/StatCard';
import { CardSkeleton } from '../components/LoadingSkeleton';
import { DataTable, type Column } from '../components/DataTable';
import { Badge } from '../components/Badge';
import { EmptyState } from '../components/EmptyState';
import { ErrorState } from '../components/ErrorState';
import type { DuplicateCluster } from '../types/api';

export function DuplicatesPage() {
  const { data: duplicates, isLoading, error } = useDuplicates();

  const getClassificationVariant = (classification: string) => {
    switch (classification) {
      case 'EXACT':
        return 'danger';
      case 'PROBABLE_DUPLICATE':
        return 'warning';
      case 'POSSIBLE_DUPLICATE':
        return 'info';
      default:
        return 'default';
    }
  };

  const columns: Column<DuplicateCluster>[] = [
    {
      key: 'id',
      header: 'Cluster ID',
      render: (row) => <span className="font-mono text-sm">#{row.id}</span>,
    },
    {
      key: 'classification',
      header: 'Classification',
      render: (row) => (
        <Badge variant={getClassificationVariant(row.classification)}>
          {row.classification.replace(/_/g, ' ')}
        </Badge>
      ),
    },
    {
      key: 'score',
      header: 'Similarity Score',
      render: (row) =>
        row.score !== null ? `${(row.score * 100).toFixed(1)}%` : 'Exact Match',
    },
    {
      key: 'member_count',
      header: 'Member Count',
      render: (row) => row.member_count.toLocaleString(),
    },
  ];

  return (
    <div className="space-y-6 pb-12">
      <PageHeader
        title="Duplicate Detection"
        description="Advisory deduplication clusters generated by the cross-source matching engine."
      />

      <div className="bg-sky-50 border border-sky-200 text-sky-800 p-4 rounded-xl shadow-sm text-sm">
        <p className="font-semibold mb-1">Advisory Notice</p>
        <p>
          Duplicate decisions are non-destructive and advisory. No records have been automatically deleted or merged in the database.
        </p>
      </div>

      {isLoading ? (
        <CardSkeleton />
      ) : error ? (
        <ErrorState message="Failed to load duplicate detection data." />
      ) : duplicates ? (
        <>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <StatCard label="Total Duplicate Clusters" value={duplicates.length.toLocaleString()} />
          </div>

          {duplicates.length === 0 ? (
            <EmptyState title="No duplicate clusters found" description="No candidate duplicate postings were detected." />
          ) : (
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <DataTable
                columns={columns}
                data={duplicates}
                keyExtractor={(item) => item.id}
              />
            </div>
          )}
        </>
      ) : null}
    </div>
  );
}
